## This code is stupid and gross but it's probably the least complicated way without adding extra libraries

CREATE_DB_STMT = """CREATE DATABASE "syria_composite_white_helmets"
  ENCODING 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8';"""

CREATE_TABLE_STMT = """CREATE TABLE iF NOT EXISTS tweets (
  id bigint NOT NULL,
  created_at varchar(64),
  created_ts timestamp,
  lang varchar(20),
  text varchar(500),
  full_text TEXT,
  geo_coordinates_0 varchar(40),
  geo_coordinates_1 varchar(40),
  contributors json,
  counts json,
  entities json,
  expanded_url TEXT,
  urls json,
  filter_level varchar(80),
  coordinates json,
  place json,
  possibly_sensitive boolean,
  _user json,
  user_id bigint,
  user_screen_name varchar(140),
  user_followers_count int,
  user_friends_count int,
  user_statuses_count int,
  user_favourites_count int,
  user_geo_enabled boolean,
  user_time_zone varchar(100),
  user_description varchar(512),
  user_location varchar(512),
  user_created_at varchar(64),
  user_created_ts timestamp,
  user_lang varchar(8),
  user_listed_count int,
  user_name varchar(140),
  user_url varchar(512),
  user_utc_offset int,
  user_verified boolean,
  user_contributors_enabled boolean,
  user_default_profile boolean,
  user_is_translator boolean,
  retweet_count int,
  favorite_count int,
  retweeted_status json,
  retweeted_status_id bigint,
  retweeted_status_user_screen_name varchar(80),
  retweeted_status_retweet_count int,
  retweeted_status_user_id bigint,
  retweeted_status_user_time_zone varchar(100),
  retweeted_status_user_friends_count int,
  retweeted_status_user_statuses_count int,
  retweeted_status_user_followers_count int,
  source varchar(500),
  in_reply_to_screen_name varchar(100),
  in_reply_to_status_id bigint,
  in_reply_to_user_id bigint,
  quoted_status_id bigint,
  quoted_status_id_str varchar(100),
  quoted_status json,
  truncated boolean,
  quoted_status_user_screen_name varchar(140),
  retweeted_status_description varchar(512),
  quoted_status_description varchar(512),
  tweet json
  );
"""

## The insertion statement for each tweet into the tweet table
INSERT_TWEET_STMT="""INSERT INTO tweets (
  id,
  created_at,
  created_ts,
  lang,
  text,
  full_text,
  geo_coordinates_0,
  geo_coordinates_1,
  contributors,
  counts,
  entities,
  expanded_url,
  urls,
  filter_level,
  coordinates,
  place,
  possibly_sensitive,
  _user,
  user_id,
  user_screen_name,
  user_followers_count,
  user_friends_count,
  user_statuses_count,
  user_favourites_count,
  user_geo_enabled,
  user_time_zone,
  user_description,
  user_location,
  user_created_at,
  user_created_ts,
  user_lang,
  user_listed_count,
  user_name,
  user_url,
  user_utc_offset,
  user_verified,
  user_contributors_enabled,
  user_default_profile,
  user_is_translator,
  retweet_count,
  favorite_count,
  retweeted_status,
  retweeted_status_id,
  retweeted_status_user_screen_name,
  retweeted_status_retweet_count,
  retweeted_status_user_id,
  retweeted_status_user_time_zone,
  retweeted_status_user_friends_count,
  retweeted_status_user_statuses_count,
  retweeted_status_user_followers_count,
  source,
  in_reply_to_screen_name,
  in_reply_to_status_id,
  in_reply_to_user_id,
  quoted_status_id,
  quoted_status_id_str,
  quoted_status,
  truncated,
  quoted_status_user_screen_name,
  retweeted_status_description,
  quoted_status_description,
  tweet
)

VALUES 

(
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s,
  %s
)"""
